### PR TITLE
add new feature

### PR DESCRIPTION
**Pull request by WadrianAraujo**
its code is the code in the world, like this now

### CODE REVIEW

**Comment by WadrianAraujo** [comment]
its code is good

**Comment by WadrianAraujo** [comment]
like code

**Comment by WadrianAraujo** [comment]
`print("hello world")`

**Review by WadrianAraujo — COMMENTED** [review]
its very good

**Review by WadrianAraujo — COMMENTED** [review]
now is more good

**Review by JulioCFSdev — APPROVED** [review]
nice

**Review by JulioCFSdev — APPROVED** [review]
nice

**Pull request merged**
